<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MonsterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('monsters')->insert([
            [
                'name' => 'Acidic Glavenus',
                'description' => '防御力ダウン。火属性弱点。',
                'image' => 'acidic Glavenus.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Alatreon',
                'description' => '火、水、雷、氷、龍属性。火活性時氷属性弱点、氷活性時火属性弱点、龍活性時龍属性弱点',
                'image' => 'alatreon.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ancient Leshen',
                'description' => '裂傷。火属性弱点。',
                'image' => 'Ancient Leshen.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Anjanath',
                'description' => '火属性。水属性弱点',
                'image' => 'anjanath.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Azure Rathalos',
                'description' => '火属性、毒。龍属性弱点',
                'image' => 'azure rathalos.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Banbaro',
                'description' => '龍属性弱点。',
                'image' => 'banbaro.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Barioth',
                'description' => '氷属性。火属性弱点',
                'image' => 'barioth.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Barroth',
                'description' => '水属性、泥。通常火属性弱点、泥纏い時水属性弱点',
                'image' => 'barroth.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bazelgeuse',
                'description' => '雷属性の力を操る古代生物。電撃をまとい、ハンターに挑む。',
                'image' => 'bazelgeuse.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Behemoth',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'behemoth.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Beotodus',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'beotodus.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Black Diablos',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'black Diablos.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Blackveil Vaal Hazak',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'blackveil Vaal Hazak.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Brachydios',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'brachydios.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Brute Tigrex',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'brute Tigrex.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Coral Pukei-Pukei',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'coral Pukei-Pukei.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Deviljho',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'deviljho.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Diablos',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'diablos.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Dodogama',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'dodogama.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ebony Odogaron',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'ebony odogaron.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Extreme Behemoth',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'extreme behemoth.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Fatalis',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'fatalis.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Frostfang Barioth',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'frostfang barioth.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Fulgur Anjanath',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'fulgur Anjanath.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Furious Rajang',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'furious rajang.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Glavenus', 
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'glavenus.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Gold Rathian',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'gold rathian.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Great Girros',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'great Girros.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Great Jagras',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'great Jagras.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jyuratodus',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'jyuratodus.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kirin',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'kirin.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kulu-Ya-ku',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'kulu-ya-ku',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kulve Taroth',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'kulve taroth',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kushala Daola',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'kushala daola',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lavasioth',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'lavasioth',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Legiana',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'legiana',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Leshen',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'leshen',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lunastra',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'lunastra',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Namielle',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'namielle',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nargacuga',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'nargacuga',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nergigante',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'nergigante',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nightshade Paolumu',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'nightshade Paolumu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Odogaron',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'odogaron',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Paolumu',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'paolumu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Pink Rathian',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'pink rathian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Pukei-Pukei',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'pukei-pukei',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Radobaan',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'radobaan',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Raging Brachydios',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'raging brachydios',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rajang',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'rajang',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rathalos',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'rathalos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rathian',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'rathian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ruiner Nergigante',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'ruiner nergigante',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Safijiiva',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'safijiiva.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Savage Deviljho',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'savage deviljho',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Scarred Yian Garuga',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'scarred yian garuga',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Seething Bazelgeuse',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'seething bazelgeuse',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Shara Ishvalda',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'shara ishvalda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Shrieking Legiana',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'shrieking legiana',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Silver Rathalos',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'silver rathalos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Stygian Zinogre',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'stygian zinogre',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Teostra',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'teostra',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tigrex',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'tigrex',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tobi-Kadachi',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'tobi-kadachi',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tzitzi-Ya-Ku',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'tzitzi-ya-ku',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Uragaan',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'uragaan',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Vaal Hazak',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'vaal hazak',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Velkhana',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'velkhana',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Viper Tobi-Kadachi',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'viper tobi-kadachi',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Xenojiva',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'Xenojiva',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Yian Garuga',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'yian garuga',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Zinogre',
                'description' => '大地を支配するかのような重厚な存在感。鋭い角と破壊力で注目を集める。',
                'image' => 'zinogre',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ]);
    }
}